### ISSUE TITLE
pycamb installation

### ISSUE THREAD

**Issue by neuronphysics** [steven-murray/hmf#16]
Hi Steven,

I would like to download your code and use it and it is like a day or two that I am fiddling around to install your code but it is kind of impossible. I can not install the version of pycamb you have suggested in the instruction because it uses CAMB version (January 2010) that I couldn't find on the web. I would be really really appreciate if you could provide a link to that version. Because when I compile other version I also get the error message that they are not compatible.

Thanks a lot and have a nice weekend.
Cheers.

**Comment by steven-murray** [comment]
Hi there,

Sorry it is not working easily for you. I have just updated the
installation guide for pycamb in its README, so you can follow those
instructions now. I cannot publicly post a link to the CAMB download, but
you should be looking for the March 2013 version (as per the new
installation notes). Finally, to get the best version of hmf installed
(presently), follow these instructions:

$ CAMBURL=<camb.url> pip install git+git://
github.com/steven-murray/pycamb.git
$ pip install git+git://github.com/steven-murray/hmf.git@develop

Cheers,
Steven

**Comment by neuronphysics** [comment]
I can not install with the procedure you have suggested. I downloaded CAMB and then copied all the *.f90 and *.F90 scripts in a folder which is named as camb inside pycamb source file and used this command line of

python setup.py install --prefix=/vol/anaconda
but I have got following error messages:


extra f90 options: '-ffree-line-length-none -O0 -g -Dintp=npy_intp -fopenmp'
gfortran:f90: camb/equations.f90
camb/equations.f90:2401.26:

    type(EvolutionVars) EV
                          1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2406.17:

    real(dl) y(EV%nvar)
                 1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2417.10:

    if (EV%no_nu_multpoles) then
          1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2419.8:

    else
        1
Error: Unexpected ELSE statement at (1)
camb/equations.f90:2420.19:

        clxr = y(EV%r_ix)
                   1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2421.7:

    end if
       1
Error: Expecting END SUBROUTINE statement at (1)
camb/equations.f90:2423.10:

    if (EV%no_phot_multpoles) then
          1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2425.8:

    else
        1
Error: Unexpected ELSE statement at (1)
camb/equations.f90:2426.19:

        clxg = y(EV%g_ix)
                   1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2427.7:

    end if
       1
Error: Expecting END SUBROUTINE statement at (1)
camb/equations.f90:2429.13:

    k    = EV%k_buf
             1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2430.13:

    k2   = EV%k2_buf
             1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2442.29:

        call MassiveNuVars(EV,y,a,grho,gpres,dgrho,dgq)
                             1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2466.14:

        if (EV%Evolve_TM) then
              1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2467.27:

            Delta_TM = y(EV%Tg_ix)
                           1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2477.27:

            Delta_xe = y(EV%xe_ix)
                           1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2488.43:

        Arr(Transfer_vnewt) = tau_fac*k*(EV%vb_newt)/H /k2
                                           1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2500.7:

    end if
       1
Error: Expecting END SUBROUTINE statement at (1)
camb/equations.f90:2396.27:

    subroutine outtransf(EV, y, Arr)
                           1
Error: Symbol 'ev' at (1) has no IMPLICIT type
camb/equations.f90:2396.30:

    subroutine outtransf(EV, y, Arr)
                              1
Error: Symbol 'y' at (1) has no IMPLICIT type
camb/equations.f90:2414.11:

    a    = y(1)
           1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2415.11:

    clxc = y(3)
           1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2416.11:

    clxb = y(4)
           1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2432.23:

    Arr(Transfer_kh) = k/(CP%h0/100._dl)
                       1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2433.24:

    Arr(Transfer_cdm) = clxc/k2
                        1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2434.22:

    Arr(Transfer_b) = clxb/k2
                      1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2435.22:

    Arr(Transfer_g) = clxg/k2
                      1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2436.22:

    Arr(Transfer_r) = clxr/k2
                      1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2443.27:

        Arr(Transfer_nu) = dgrho/grho/k2
                           1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2458.24:

    Arr(Transfer_tot) = dgrho/grho/k2
                        1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2471.13:

        vb = y(5)
             1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2482.29:

        z=(0.5_dl*dgrho/k + y(2))/H
                             1
Error: Function 'y' at (1) has no IMPLICIT type
Fatal Error: Error count reached limit of 25.
camb/equations.f90:2401.26:

    type(EvolutionVars) EV
                          1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2406.17:

    real(dl) y(EV%nvar)
                 1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2417.10:

    if (EV%no_nu_multpoles) then
          1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2419.8:

    else
        1
Error: Unexpected ELSE statement at (1)
camb/equations.f90:2420.19:

        clxr = y(EV%r_ix)
                   1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2421.7:

    end if
       1
Error: Expecting END SUBROUTINE statement at (1)
camb/equations.f90:2423.10:

    if (EV%no_phot_multpoles) then
          1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2425.8:

    else
        1
Error: Unexpected ELSE statement at (1)
camb/equations.f90:2426.19:

        clxg = y(EV%g_ix)
                   1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2427.7:

    end if
       1
Error: Expecting END SUBROUTINE statement at (1)
camb/equations.f90:2429.13:

    k    = EV%k_buf
             1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2430.13:

    k2   = EV%k2_buf
             1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2442.29:

        call MassiveNuVars(EV,y,a,grho,gpres,dgrho,dgq)
                             1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2466.14:

        if (EV%Evolve_TM) then
              1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2467.27:

            Delta_TM = y(EV%Tg_ix)
                           1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2477.27:

            Delta_xe = y(EV%xe_ix)
                           1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2488.43:

        Arr(Transfer_vnewt) = tau_fac*k*(EV%vb_newt)/H /k2
                                           1
Error: Name 'ev' at (1) is an ambiguous reference to 'ev' from current program unit
camb/equations.f90:2500.7:

    end if
       1
Error: Expecting END SUBROUTINE statement at (1)
camb/equations.f90:2396.27:

    subroutine outtransf(EV, y, Arr)
                           1
Error: Symbol 'ev' at (1) has no IMPLICIT type
camb/equations.f90:2396.30:

    subroutine outtransf(EV, y, Arr)
                              1
Error: Symbol 'y' at (1) has no IMPLICIT type
camb/equations.f90:2414.11:

    a    = y(1)
           1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2415.11:

    clxc = y(3)
           1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2416.11:

    clxb = y(4)
           1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2432.23:

    Arr(Transfer_kh) = k/(CP%h0/100._dl)
                       1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2433.24:

    Arr(Transfer_cdm) = clxc/k2
                        1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2434.22:

    Arr(Transfer_b) = clxb/k2
                      1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2435.22:

    Arr(Transfer_g) = clxg/k2
                      1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2436.22:

    Arr(Transfer_r) = clxr/k2
                      1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2443.27:

        Arr(Transfer_nu) = dgrho/grho/k2
                           1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2458.24:

    Arr(Transfer_tot) = dgrho/grho/k2
                        1
Warning: Possible change of value in conversion from REAL(8) to REAL(4) at (1)
camb/equations.f90:2471.13:

        vb = y(5)
             1
Error: Function 'y' at (1) has no IMPLICIT type
camb/equations.f90:2482.29:

        z=(0.5_dl*dgrho/k + y(2))/H
                             1
Error: Function 'y' at (1) has no IMPLICIT type
Fatal Error: Error count reached limit of 25.
error: Command "/usr/bin/gfortran -Wall -g -fno-second-underscore -fPIC -O2 -I/vol/anaconda/lib/python2.7/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-2.7 -I/vol/anaconda/lib/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c -c camb/equations.f90 -o build/temp.linux-x86_64-2.7/camb/equations.o -Jbuild/temp.linux-x86_64-2.7/pycamb -Ibuild/temp.linux-x86_64-2.7/pycamb -ffree-line-length-none -O0 -g -Dintp=npy_intp -fopenmp" failed with exit status 1

any suggestion?

**Comment by steven-murray** [comment]
Hi,

Hmmm, that is strange. Can you confirm the version of camb you downloaded? It should be the March 2013 version, otherwise it will probably not work.

**Comment by neuronphysics** [comment]
Hi,

I have used this version: http://camb.info/sources/downred/CAMB_sources.zip

**Comment by steven-murray** [comment]
Ah, that is not the correct code -- you want the main CAMB code, not CAMB_sources (that is more to do with 21cm stuff it seems). I assume you have filled out the form online and gotten the email to tell you where to download CAMB?

**Comment by neuronphysics** [comment]
yes, That is how I could download it.

**Comment by steven-murray** [comment]
okay, so try installing like this (I'll have to remove this comment shortly after I post it, as it should not be posted publicly...):

    CAMBURL=http://camb.info/CAMB_Mar13.tar.gz pip install git+git:// github.com/steven-murray/pycamb.git

**Comment by neuronphysics** [comment]
Thanks Steven. I could install pycamb but not with using pip because I don't have root access to my machine. Now I could import pycam but when I try to run the example you have posted I get this error message
 File "<stdin>", line 1, in <module>
  File "/vol/anaconda/lib/python2.7/site-packages/pycamb/__init__.py", line 136, in camb
    cls=_getcls(pvec,lmax,max_eta_k)
TypeError: Required argument 'cls' (pos 4) not found

**Comment by steven-murray** [comment]
That is very strange... maybe it's a compiler thing? 
I guess you need to check which version of gfortran you have, and which version of numpy and f2py as well. 
In my code, I have the same line, and it doesn't complain, as far as I'm aware. 

Also, which example were you trying? If you only need to use pycamb for hmf, just try the examples in the hmf docs -- you only ever need a single function from pycamb (``.transfer()``).

**Comment by neuronphysics** [comment]
My gfortran's version is 4.8.4 and I have 1.10.1 ,2 versions of numpy and f2py respectively.

**Comment by steven-murray** [comment]
Okay, that should all work. It must be the camb source code which is not correct.

Try the following steps:
```
$ rm -rf /vol/anaconda/lib/python2.7/site-packages/pycamb
$ cd ~
$ git clone https://github.com/steven-murray/pycamb.git
$ cd pycamb
$ wget http://camb.info/CAMB_Mar13.tar.gz
$ tar -xvzf CAMB_Mar13.tar.gz
$ python setup.py install
$ cd ..
$ ipython
>>> import pycamb
>>> pycamb.transfers() #<-- the only function that needs to be called for hmf to work
```

I just did that exactly (except the first line of course) in a clean environment on my system, and it worked. If that doesn't work for you, I'm not sure how to fix it!

**Comment by inonchiu** [comment]
Hi Steven,

The solution you provided above is quite nice, thanks! I was also encountering some difficulties regarding the pycamb and hmf, but it is solved now. Just wonder whether you have plan to implement the latest python wrapper of camb, which is also now in the official camb release, to your mass function code?

Thanks a lot!

**Comment by steven-murray** [comment]
@inonchiu I'm glad that it worked for you. I have just removed it, because you need to find the download link yourself -- there's a terms and conditions form that you need to confirm which I should not bypass. 

As far as the "python wrapper" is concerned, I cannot see a proper wrapper anywhere in the CAMB source -- there are some python scripts for plotting results, but not for interacting with the f90 code.

Just to be clear to all in the future, the steps to get to the link are:
1. Go to http://camb.info/CAMBsubmit.html
2. Fill out the form
3. Check your email, and follow the link provided.
4. Copy the link location of the CAMB_Mar13.tar.gz link on that page
5. Use ``--get=copied-link`` when installing pycamb.

**Comment by steven-murray** [comment]
Closing this unless anyone else has a problem.
