### ISSUE TITLE
py.test error after intall

### ISSUE THREAD

**Issue by yuanshuoastro** [steven-murray/hmf#17]
Hi Steven,
I install the pycamb and hmf(release1.8.0) from you github.
No errors during installing. But when I try the py.test in your ./test dir, I meet the Failure:

=================================== FAILURES ===================================
___________________________ TestFcoll.test_fcolls[0] ___________________________

self = <test_fcoll.TestFcoll object at 0x7f8175af95d0>
pert = <hmf.hmf.MassFunction object at 0x7f8175af9850>, fit = 'PS'

```
def check_fcoll(self, pert, fit):
    if fit == "PS":
        anl = fcoll_PS(np.sqrt(pert.nu))
        num = pert.rho_gtm / pert.mean_dens

    elif fit == "Peacock":
        anl = fcoll_Peacock(np.sqrt(pert.nu))
        num = pert.rho_gtm / pert.mean_dens

    err = np.abs((num - anl) / anl)
    print np.max(err)
    print num / anl - 1
```

> ```
>   assert np.max(err) < 0.05
> ```
> 
> E       assert 1.1693592892307125 < 0.05
> E        +  where 1.1693592892307125 = <function amax at 0x7f817e4ab050>(array([  2.46884309e-01,   2.46889912e-01,   2.46894728e-01,\n         2.468987...  1.09377128e+00,   1.11834393e+00,\n         1.14353402e+00,   1.16935929e+00]))
> E        +    where <function amax at 0x7f817e4ab050> = np.max

Do you think it is OK? What else should I do?

Thanks!
Shuo

**Comment by steven-murray** [comment]
Hi Shuo,

That is odd, since the tests seem to pass on my machine. What it means is
that the integral of the mass-weighted Press-Schechter function is not
equalling the total mean density, which it should.

Try installing hmf like this: ``pip install git+git://
github.com/steven-murray/hmf.git@develop``. This will install the latest
development version. To run the tests, clone the develop branch, and run
"nosetests -v" in the top directory. If that still fails, let me know!

Cheers,
Steven

**Comment by yuanshuoastro** [comment]
Hi Steven,

I tried again. 
If I git clone the master branch, and run "nosetests -v" in the top directory, I got everything OK. IF I clone the dev branch, I got massive wrong after "nosetests -v" running.

So I should use the master branch to install in my computer?

Thanks!
Shuo

**Comment by steven-murray** [comment]
Perhaps that is a good option for now, until I can figure out what's going wrong here. I'll let you know.

Cheers,
Steven

**Comment by steven-murray** [comment]
Never did figure this out, but things have evolved a lot.
