### ISSUE TITLE
Additional factor 1e6 in hmf/cosmo.py:105

### ISSUE THREAD

**Issue by iw381** [steven-murray/hmf#28]
The additional factor `1e6` in `hmf/cosmo.py:105` could be removed if the prepending `M` (mega) at the unit conversiton from grams to solar masses is removed as well:
```python
>>> u.solMass.to(u.kg)
1.9891e+30

>>> u.MsolMass.to(u.kg)
1.9891e+36
```

**Comment by steven-murray** [comment]
Awesome, thanks for that. Fixed in 2af79141aad238351781733a2da3ee820e97ea3f
