### ISSUE TITLE
Default values for sigma8 and n in hmf/transfer.py

### ISSUE THREAD

**Issue by iw381** [steven-murray/hmf#29]
In the initialisation of the `Transfer` class in `hmf/transfer.py`, there are still the old Planck13 parameters used as default values for n_s (`n=0.9624`) and sigma_8 (`sigma_8=0.8344`). 
It would be reasonable to update these, since in the initialisation of the `Cosmo` class Planck15 is used as default parameter set for all other cosmological parameters.

Planck 2015 parameters are:
    `n = 0.9667` 
    `sigma_8 = 0.8159`

**Comment by steven-murray** [comment]
thanks a lot for noticing that. Fixed in 257bcf105c357c34eae09b2ce06c8803f697e7a0 and version bumped to 2.0.1
