### ISSUE TITLE
How can I get CAMB

### ISSUE THREAD

**Issue by neuronphysics** [steven-murray/hmf#3]
Hi,

I am trying to download and install your halo mass function code in my machine. I am wondering how I can obtain camb or what is the email address for this code in order to run this command
python setup.py install [--get=www.address-where-camb-code-lives.org]

on the other hand I don't have root permission, how could I install the code in this case?

Thanks in advance.

**Comment by steven-murray** [comment]
Hi there,

I refer you to the camb website: http://camb.info. From there you will find the downloads (you will be required to tick a box or two and check your email for the relevant final url). Once you have the download url for the specific version of CAMB you like, you can do one of two things:

1. Download the source into the pycamb/ distribution folder and unzip it, and run the install.
2. Run ``python setup.py install --get=<url>`` where the url is the one for the download (should end with a .tar.gz). 

To install without root permission, you have a few options (look it up on google there should be heaps of info). My preferred method is to use the Anaconda python distribution, which installs locally to wherever you want it to. Another method is to use a flag in the python setup.py install command that installs the package locally.

Hope that helps!

**Comment by neuronphysics** [comment]
Hi again,

Thanks for the tips. I did install pycamb with the command like you have suggested. I got some warning during installation process such as
build/src.linux-x86_64-2.7/src/_pycamb-f2pywrappers2.f90:200.10:

      use pycamb_mod, only : matter_power_sigma8
          1
Warning: Unused module variable 'matter_power_sigma8' which has been explicitly imported at (1)
build/src.linux-x86_64-2.7/src/_pycamb-f2pywrappers2.f90:200.10:

      use pycamb_mod, only : matter_power_sigma8
          1
Warning: Unused module variable 'transfers' which has been explicitly imported at (1)
build/src.linux-x86_64-2.7/src/_pycamb-f2pywrappers2.f90:200.10:

      use pycamb_mod, only : matter_power_sigma8
          1
Warning: Unused module variable 'transfers_k' which has been explicitly imported at (1)
build/src.linux-x86_64-2.7/src/_pycamb-f2pywrappers2.f90:200.10:

      use pycamb_mod, only : matter_power_sigma8
          1
Warning: Unused module variable 'transfers_sigma8' which has been explicitly imported at (1)

 Then I have installed hmf without any error but when I try to  run it with your given example I got this error
>>> from hmf import MassFunction
>>> hmf = MassFunction()
>>> mass_variance = hmf.sigma
Segmentation fault (core dumped)
 and it crashed. I don't know what might be a problem. I will appreciate if you could help.

Thanks.

**Comment by steven-murray** [comment]
That's interesting. The warnings are fine as far as I know. I've never gotten a segfault with pycamb on default settings before. I don't think I'll be able to help much unless I know your OS, compiler, python version and numpy version.

**Comment by steven-murray** [comment]
Hi, I hope you were able to get this working. Let us know if it's still a problem, or what the solution was, but otherwise I am going to close this.
