### ISSUE TITLE
Bug in hmf/hmf/transfer_models.py

### ISSUE THREAD

**Issue by yin01** [steven-murray/hmf#30]
Hi Steven,

There seems to be a typo in hmf/hmf/transfer_models.py in line 288 of class EH_BAO. np.exp(-(k * self.cosmo.h / kSilk) should be replaced by np.exp(-(k/ kSilk) as k is in Mpc^{-1} unit. And by changing this, you can match the original codes from Hu's website (http://background.uchicago.edu/~whu/transfer/tf_fit.c, you can find the same line if you search exp(-pow(k/k_silk,1.4)). Can you verify this please. Thanks!

Best,
Yin

**Comment by steven-murray** [comment]
Hi Yin,

Thank you for your report. I am not sure that it is a bug however. In the original code, all units have no hubble constant. But in hmf, k is expected to be passed in the units of h/Mpc, so it needs to be multiplied by h to get it into Mpc^-1 as required.

Let me know if I've got this wrong!
Cheers,
Steven
On Jun 5 2016, at 2:01 am, yin01 <notifications@github.com> wrote:

Hi,

There seems to be a typo in hmf/hmf/transfer_models.py in line 288 of class EH_BAO. np.exp(-(k * self.cosmo.h / kSilk) should be replaced by np.exp(-(k/ kSilk) as k is in Mpc^{-1} unit. And by changing this, you can match the original codes from Hu's website (http://background.uchicago.edu/~whu/transfer/tf_fit.c<http://background.uchicago.edu/%7Ewhu/transfer/tf_fit.c>, you can find the same line if you search exp(-pow(k/k_silk,1.4)). Can you verify this please. Thanks!

Best,
Yin

**Comment by yin01** [comment]
Hi Steve,

Thank you for your response! It was my mistake, the line I wanted to point out was actually line 289

Tb = np.sinc(k * stilde / np.pi) * (Tb1 + Tb2)

which should be 

Tb = np.sinc(k * self.cosmo.h  * stilde / np.pi) * (Tb1 + Tb2)

Let me know if this is right!

Best,
Yin

**Comment by yin01** [comment]
Thanks Steven! After changing that, the result matches with the original code!

**Comment by steven-murray** [comment]
Thanks!
