### ISSUE TITLE
Changing power spectrum

### ISSUE THREAD

**Issue by adnanuw** [steven-murray/hmf#43]
I am not sure if this is the right place for the question. If not, please direct me accordingly. 
Q: I am trying to create halo mass functions using a custom power spectrum. I am curious how I may be able to change the power spectrum such that the halo mass function is calculated using the new power spectrum. 

Thank you for your help.

**Comment by steven-murray** [comment]
This is a perfect place to ask these questions! 

You can change the power spectrum to any of the forms in the `hmf.transfer` model. These include CAMB and Eisenstein and Hu. One of the forms accepts an arbitrary array of k and T. 

Does that help?

**Comment by steven-murray** [comment]
More explicitly, you can do something like this:

```python
from hmf import MassFunction

mf = MassFunction(transfer_model="FromFile", transfer_params={"fname":"your_file_with_transfer_function.txt"})
```

The file should have two columns: `k` and `transfer`, in that order.

**Comment by adnanuw** [comment]
Hi Steven,

Thank you so much for your prompt response.

I am trying to do the following and was curious if you may have any
thoughts:
- I have calculated a growth factor from a new cosmological model and want
to see its implication on the number density of halos. I tried to do this
by inputting the new power spectrum I evaluated using the new growth factor
but when I plotted the new number density of halos, it is exactly the same
as before. This may be because the code normalizes the power spectrum with
sigma8 to match the cosmology, and somehow results in the same halo mass
function. I was curious if you have any thoughts on how to find the effect
of a new growth factor on the halo mass function using your code.

Best,
Adnan

**Comment by steven-murray** [comment]
Hi Adnan, sorry for the slow response! Yes, the code normalises the power spectrum to match sigma8. If you have a method for generating the growth factor that is different to those included in hmf, you may write your own class and use that. 

To get an idea of how to do this, look in the growth module. If you copy the interface, but change the calculation method, you can do anything you like!

As a minimal example, consider the following file:

```python
from hmf.growth_factor import GrowthFactor

class MyGrowthFactor(GrowthFactor):
    """
    My new growth factor calculation
    """
    # Include some defaults if you require some adjustable parameters
    # _defaults = {"dz":0.01, "zmax":1000.0}

    def growth_factor(self, z):
        """
        The growth factor, :math:`d(a) = D^+(a)/D^+(a=1)`.

        Parameters
        ----------
        z : array_like
            Redshift.

        Returns
        -------
        gf : array_like
            The growth factor at `z`.
        """
        # Obviously, this is a very silly growth factor, but put what you want in.
        return z**3

    def growth_factor_fn(self, zmin=0.0, inverse=False):
        """
        Return the growth factor as a callable function.

        Parameters
        ----------
        zmin : float, optional
            The minimum redshift of the function. Default 0.0

        inverse: bool, optional
            Whether to return the inverse relationship [z(g)]. Default False.

        Returns
        -------
        callable
            The normalised growth factor as a function of redshift, or
            redshift as a function of growth factor if ``inverse`` is True.

        """
        if not inverse:
            return self.growth_factor
        else:
            self._zvec = np.arange(zmin, self.params['zmax'], self.params['dz'])
            gf = self.growth_factor(self._zvec)
            return _spline(gf[::-1], self._zvec[::-1])

from hmf import MassFunction

mf = MassFunction(growth_model=MyGrowthFactor, growth_params={<any_params_you_want_to_change_from_default>})
```

This will work (and be a very bad model!). 

Let me know if this makes sense and works for you, or if you need more help.
