### ISSUE TITLE
Quickstart fails

### ISSUE THREAD

**Issue by timothydmorton** [steven-murray/hmf#45]
﻿Just trying to run the quickstart example fails for me:
<img width="1048" alt="Screenshot 2020-03-20 23 10 37" src="https://user-images.githubusercontent.com/1895387/77220756-58ab1300-6b00-11ea-9456-315c7075f3f3.png">

**Comment by steven-murray** [comment]
Thanks for the report -- I will have a look ASAP. It's most likely a
documentation bug.
