### ISSUE TITLE
From the scripts accuracy_test.py 

### ISSUE THREAD

**Issue by StephenJTurnbull** [steven-murray/hmf#5]
What simple 'test everything works, plot a simple HMF for default conditions do you recommend breaking one's teeth on first?

I tried accuracy_test.py and it returned the following error. 

File "accuracy_test.py", line 112, in main 
accuracy_args.add_argument("--lnk-min", nargs="*", type=float,
                                                        help="the maximum wavenumber [default: %s]" %
>                                                      h.transfer.lnk[0])
AttributeError: 'numpy.ndarray' object has no attribute 'lnk'
accuracy_test.py: AttributeError("'numpy.ndarray' object has no attribute 'lnk'",)
                  for help use --help

I tried to redo the same action in Ipython and got a different error.

***********************************************************************************************
In [11]: h = MassFunction()
In [12]: h.transfer
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/home/sjturnbu/<ipython-input-12-d9166685ed1c> in <module>()
----> 1 h.transfer
/usr/local/lib/python2.7/dist-packages/hmf/_cache.pyc in _get_property(self)
---> 52                 value = f(self)
/usr/local/lib/python2.7/dist-packages/hmf/transfer.pyc in transfer(self)
--> 456             return self._lnT_cdm
/usr/local/lib/python2.7/dist-packages/hmf/_cache.pyc in _get_property(self)
---> 52                 value = f(self)
/usr/local/lib/python2.7/dist-packages/hmf/transfer.pyc in _lnT_cdm(self)
--> 401                                self._unnormalised_lnT,
/usr/local/lib/python2.7/dist-packages/hmf/_cache.pyc in _get_property(self)
---> 52                 value = f(self)
/usr/local/lib/python2.7/dist-packages/hmf/transfer.pyc in _unnormalised_lnT(self)
--> 377             return get_transfer(self.transfer_fit, self).lnt(self.lnk)
/usr/local/lib/python2.7/dist-packages/hmf/transfer.pyc in get_transfer(name, t)
---> 31         return getattr(sys.modules[__name__], name)(t)
TypeError: getattr(): attribute name must be string

***********************************************************************************************
It is clearly finding the /hmf/transfer.pyc code ... but fails after that.

**Comment by steven-murray** [comment]
Hmmm can I check which version you have? Can you download the master branch of this git repo and "python setup.py install" it? I think some of those errors come from a previous version.

**Comment by StephenJTurnbull** [comment]
I did a re-install from master, as suggested:

version went from 1.7 to 1.8 
and the location changed to add "hmf-1.8.0-py2.7.egg"
Location: /usr/local/lib/python2.7/dist-packages/hmf-1.8.0-py2.7.egg

I tried running all the scripts from the scripts directory:

accuracy_test.py: AttributeError("'MassFunction' object has no attribute 'transfer'",) 

File "benchmarks.py", line 13, in <module>
   ImportError: No module named Perturbations

code_comparison.py
    from hmf import Perturbations
ImportError: cannot import name Perturbations

hmf: AttributeError("'module' object has no attribute 'Fits'",)

    from hmf import Perturbations
ImportError: cannot import name Perturbations

Transfer_limits.py: 
Works and outputs sensible things but does have one runtime warning.
/usr/local/lib/python2.7/dist-packages/hmf-1.8.0-py2.7.egg/hmf/transfer.py:91: RuntimeWarning: invalid value encountered in log




After Reinstall from Master: 
******************************************************************************************************
 pip show hmf
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
---
Metadata-Version: 1.0
Name: hmf
Version: 1.8.0
Summary: A halo mass function calculator
Home-page: https://github.com/steven-murray/hmf
Author: Steven Murray
Author-email: steven.murray@uwa.edu.au
License: MIT
Location: /usr/local/lib/python2.7/dist-packages/hmf-1.8.0-py2.7.egg
Requires: numpy, scipy, cosmolopy, emcee

**Comment by steven-murray** [comment]
Hi Stephen,

Excellent. Looks like the update fixed things. The `code_comparison` and `benchmarks` files were written more for my own testing of things, and probably haven't been updated for a while, breaking some things (like eg. import names!) So don't worry about those. To test that things are all working, the best thing to do is to run the nosetests (these all run fine on my system, and also the Travis-CI system). 

If you want to just run some default kinds of things and plot them up, you might want to try the following:

```python
from hmf import MassFunction
import numpy as np
import matplotlib.pyplot as plt

h = MassFunction(mf_fit="ST")
for z in np.linspace(0,1,8):
    h.update(z=z)
    plt.plot(h.M,h.dndlnm,label="z=%s"%z)

plt.legend(loc=0)
plt.savefig("hmf_z.pdf")
```
That should give you a plot of several mass functions at different redshifts. Of course, it depends on your final application as to what you should be testing works ;)

If you like, let me know your basic final application and I'll give some pointers at how to use the code efficiently in that case.
