### ISSUE TITLE
Problem with density_field.halofit.halofit

### ISSUE THREAD

**Issue by andrearubiola** [steven-murray/hmf#94]
Using Python3.8 and Anaconda 3, hmf version: that installed via pip, I suppose 3.0.8 

Dear Sirs,

I was trying to use  hmf software in order to obtain a nonlinear no-wiggles P(k) starting from nbodykit linear no-wiggles P(k) at z=1.35 and standard lambdaCDM cosmology.
The basic idea would be using density_field.halofit.halofit as a quick "converter" from nbodykit spectra.
However, while running halofit.halofit I first came across the following error

       "Lowest R not low enough in _get_spec. ln(sig) starts below 0: ",
 
Reading halofit source code, I thought it was due to this:

```
if 0.6 < sigma_8 > 1.0:
        lnr = np.linspace(np.log(0.1), np.log(10.0), 500)
        lnsig = np.empty(500)

    else:  # weird sigma_8 means we need a different range of r to go through 0.

```

In fact, why sigma_8=0.8 should be "weird"?
I modified the code:  0.6 < sigma_8 < 1.0, but now I'm having another kind of troubles:

```
/home/andrea/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/hmf/density_field/halofit.py:74: RuntimeWarning: divide by zero encountered in double_scalars
  rknl = 1.0 / np.exp(r_of_sig(0.0))
/home/andrea/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/hmf/density_field/halofit.py:78: RuntimeWarning: divide by zero encountered in log
  dev1, dev2 = sig_of_r.derivatives(np.log(1.0 / rknl))[1:3]
/home/andrea/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/hmf/density_field/halofit.py:80: UserWarning: Requiring extra iterations to find derivatives of sigma at 1/rknl (this often happens at high redshift).
  warnings.warn(
/home/andrea/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/hmf/density_field/halofit.py:84: RuntimeWarning: divide by zero encountered in log
  lnr = np.linspace(np.log(0.2 / rknl), np.log(5 / rknl), 100)
/home/andrea/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/numpy/core/function_base.py:127: RuntimeWarning: invalid value encountered in double_scalars
  delta = stop - start

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/hmf/density_field/halofit.py in _get_spec(k, delta_k, sigma_8)
     77     try:
---> 78         dev1, dev2 = sig_of_r.derivatives(np.log(1.0 / rknl))[1:3]
     79     except Exception:

~/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/scipy/interpolate/fitpack2.py in derivatives(self, x)
    424         if not ier == 0:
--> 425             raise ValueError("Error code returned by spalde: %s" % ier)
    426         return d

ValueError: Error code returned by spalde: 10

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-9-316a3c09eb12> in <module>
----> 1 pnlw=density_field.halofit.halofit(ktotal,pnorm, sigma_8, zbin, cosmo=my_cosmo, takahashi=True) #Generate (?) non-linear wiggles with halofit
      2 pnlnw=density_field.halofit.halofit(ktotal,pnorm_nw, sigma_8, zbin, cosmo=my_cosmo, takahashi=True) #Generate (?) non-linear no-wiggles with halofit

~/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/hmf/density_field/halofit.py in halofit(k, delta_k, sigma_8, z, cosmo, takahashi)
    135 
    136     # Get physical parameters
--> 137     rknl, neff, rncur = _get_spec(k, delta_k, sigma_8)
    138 
    139     # Only apply the model to higher wavenumbers

~/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/hmf/density_field/halofit.py in _get_spec(k, delta_k, sigma_8)
     95             raise Exception("Lots of things went wrong in halofit")
     96 
---> 97         sig_of_r = _spline(lnr, lnsig, k=5)
     98         dev1, dev2 = sig_of_r.derivatives(np.log(1.0 / rknl))[1:3]
     99 

~/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/scipy/interpolate/fitpack2.py in __init__(self, x, y, w, bbox, k, ext, check_finite)
    618                  ext=0, check_finite=False):
    619 
--> 620         x, y, w, bbox, self.ext = self.validate_input(x, y, w, bbox, k, None,
    621                                             ext, check_finite)
    622         if not np.all(diff(x) > 0.0):

~/anaconda3/envs/nbodykit-env/lib/python3.8/site-packages/scipy/interpolate/fitpack2.py in validate_input(x, y, w, bbox, k, s, ext, check_finite)
    195         if s is None or s > 0:
    196             if not np.all(diff(x) >= 0.0):
--> 197                 raise ValueError("x must be increasing if s > 0")
    198         else:
    199             if not np.all(diff(x) > 0.0):

ValueError: x must be increasing if s > 0

```

I'm a bit puzzled and I'm not able to figure out a solution.

[minimal_example.txt](https://github.com/steven-murray/hmf/files/5246739/minimal_example.txt)
[minimal_example.pdf](https://github.com/steven-murray/hmf/files/5246740/minimal_example.pdf)

In attachment, both the the pdf of the notebook I'm using and the txt if you wish to run it as a .py file.

Thanks in advance,

Best regards

Andrea

**Comment by steven-murray** [comment]
Thanks @andrearubiola for the detailed report. This is a use-case I haven't previously encountered, so it's a great opportunity to tighten up the code! 

It looks like you're doing everything right in your example, so it looks like it might be a bug in `hmf`. Certainly, the very strange double-sided comparison of `sigma_8` is quite strange. I haven't touched the `halofit` code in quite a while, so it may take me a bit to figure out where the problem is. I'll try get it to this week. Feel free to ping me if I take too long!

**Comment by andrearubiola** [comment]
Thanks for your answer. I have overcome the problem by using the Transfer
function framework to produce my non-linear power spectra, so, as far as
I'm concerned, my issue is solved. Anyway, I'll stay tuned: halofit.halofit
is more straightforward and transfer function-independent, it would be a
pity not having it fully working.

Best regards

Andrea Rubiola

Il lun 21 set 2020, 20:56 Steven Murray <notifications@github.com> ha
scritto:

**Comment by steven-murray** [comment]
Great to hear you found a workaround! Gives me a little more time to try and fix the issue :-)

**Comment by andrearubiola** [comment]
Hello, I hope I'm not bothering anybody. Just out of curiosity, how are
things doing with the supposed bug I signalled in this thread?
Andrea

Il lun 21 set 2020, 21:45 Steven Murray <notifications@github.com> ha
scritto:

**Comment by steven-murray** [comment]
Hi @andrearubiola, sorry I have not had a chance to get to it. I have a conference early next week to prepare for. I've set this on my agenda for next Wednesday... here's hoping :-)

**Comment by steven-murray** [comment]
Hi @andrearubiola, I have run this (having changed it to `0.6 < sigma_8 < 1.0`) and it seems to run through perfectly fine. I cannot seem to get `nbodykit` installed on my system, so perhaps there's something odd going on with it? Can you maybe print out the actual values of `pnorm` you're getting from `nbodykit`? At the moment, I am simply taking a spline of the `power` from `hmf`, and evaluating it at `ktotal`, and passing that into `halofit`. That works perfectly fine.

**Comment by andrearubiola** [comment]
Dear Steven,

Thanks for your update; first thing first, I don't have to signal any
incompatibility issue between hmf and nbodykit, I'm using them and the guys
make together a brilliant team!

Concerning your question, I've uninstalled and reinstalled hmf so to be
sure that I was starting from a clean software.
Once installed, I have modified the halofit.py script by fixing the
if-condition on sigma.
Unfortunately, when densityfield.halofit.halofit is called inside the
minimal_example.py, another error is returned:

'function' object has no attribute 'halofit'

Honestly, neither do I remember if this happened also the first time I
installed  HMF in September nor how I fixed the error at the time (if
I had to).
I suppose there's some problem in how the various packages are
searched and called when they are run. I suggest there may be some
trouble in the whole density_field

folder and how the packages are talking each other and being invoked.
Maybe, once fixed the package calling problem, also the other issues I
signalled would

finally disappear (I'm working with HMF as it can be downloaded from pip)

Since September, I've not been making any other experiment with HMF
apart from the routine use of it I mentioned at the beginning of the
email, but I

can add a little piece of information which I hope could be useful: I
made some HMF Halofit (via the transfer function workaround I
mentioned previously) vs Nbodykit Halofit
power spectrum and the two do not superpose exactly. The two
algorithms might be slightly different from the very beginning, then.

Given this difference, I have concluded that the best way to use
Halofit together with Nbodykit is feeding transferfunction with linear
nbodykit power spectra
 (with and without wiggles) and extracting the corresponding
non-linear PK, rather than using Nbodykit for the wiggles PK and hmf
for  the no-wiggles PK.

Best regards,

Andrea




Il giorno mer 25 nov 2020 alle ore 23:49 Steven Murray <
notifications@github.com> ha scritto:

**Comment by steven-murray** [comment]
Hi @andrearubiola  -- thanks for the feedback! Yes, in the newest version of hmf you just need to do `from hmf.density_field import halofit` and that is the function itself (i.e. you don't need to do `from hmf.density_field.halofit import halofit`). The if-statement is also fixed in the latest version.

There is definitely the possibility that `halofit` in `hmf` won't line up perfectly with another implementation. Getting the non-linear scale and the effective index/curvature are not trivial and depend slightly on the exact interpolation being done etc. This should be good to ~1% though.  

I hope that helps!

**Comment by andrearubiola** [comment]
Good (CET) afternoon,
I'm sorry, but the HMF version I download from pip install hmf still contains the wrong if-statement and, even once I've fixed it by hand, the script crashes. 
I've got a suspicion: are you still maintaining and updating hmf on pip or do I have to download it from github to get the latest and working version? 
Best regards

**Comment by steven-murray** [comment]
Hi @andrearubiola, sorry I was wrong -- I hadn't merged the lastest updates to master yet (once merged to master, they are automatically deployed to PyPI). The changes are in v3.3.1 which should be up now (on PyPI).

**Comment by andrearubiola** [comment]
Hi Steven, 
I confirm, now hmf is working fine. I'd suggest updating in the documentation how the custom cosmology is called: before one had to do `from hmf import cosmology as cm my_cosmo = cm.Cosmology()`  and then pass `cosmo=my_cosmo` in halofit, now instead one has to pass `cosmo=my_cosmo.cosmo.` otherwise the program crashes;  I suppose you've changed a little bit the structure of packages and dependencies.
Plotted the two halofit and I confirm in the BAO region a difference of +- 4% in the ratio HMF/Nbodykit with Takahashi either True or False; beyond this region, HMF calculation is steadily 96% of Nbodykit's.
For the rest, it's working really fine!
That's it, cheers
Andrea

**Comment by steven-murray** [comment]
@andrearubiola thanks for the report! I will make an issue to help myself to remember to update the docs. And another one to remind me to check correspondence between Nbodykit and hmf for halofit :-)
