### ISSUE TITLE
[BUG] Dependency importlib_metadata missing

### ISSUE THREAD

**Issue by Stefan-Heimersheim** [steven-murray/hmf#98]
**Describe the bug**
`import hmf` returns an error missing the module `importlib_metadata`. This does not seem to happen on all systems, but on our cluster it seems to do. Does it need to be added as a dependency?

**To Reproduce**
1. `pip3 instal hmf --user`
2. `python3`
3. `import hmf`

**Expected behavior**
It should not return an error and just import the `hmf` module. System information:
- RHEL 7
 - Python 3.6.8
 - hmf-3.2.1

**Actual behaviour**
```
>>> import hmf
Traceback (most recent call last):
  File "/home/sh2061/.local/lib/python3.6/site-packages/hmf/__init__.py", line 2, in <module>
    from importlib.metadata import version, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sh2061/.local/lib/python3.6/site-packages/hmf/__init__.py", line 4, in <module>
    from importlib_metadata import version, PackageNotFoundError
ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by steven-murray** [comment]
Interesting! I'll look into it ASAP :-)
