### ISSUE TITLE
[Feature Req] Critical density and density contrast

### ISSUE THREAD

**Issue by domeckert** [steven-murray/hmf#99]
Hello! Thanks for your work with HMF, it is a really useful package.

I was using the Py2 version until recently and regularly used the "delta_wrt='crit'" and "delta_h=500" options to set the overdensity with respect to the critical density and the density contrast to 500 (which is the default in the galaxy cluster community).  I am now on Py3 on Ubuntu 20.04 (which doesn't support Py2 any more) and I now see that these options are not present any more. Would it be possible to implement these features again the Py3 version?

**Comment by steven-murray** [comment]
Hi @domeckert. Thanks for using hmf! 

These features have not gone away, instead they are more general than before :-) You now explicitly pass a mass definition. For what you were asking, you'd do

```python
mf = MassFunction(mdef_model='SOCritical', mdef_params={'overdensity':500})
```

Note that some of the fitting functions have been updated to automatically know which kind of mass-definition they were originally measured in, and they won't compute for a different model. If you are using Tinker mf, this should be OK.

**Comment by domeckert** [comment]
Awesome! Thanks a lot @steven-murray
